apiVersion: v1
kind: Service
metadata:
  name: my-app-service
  labels:
    app: my-app
spec:
  type: LoadBalancer # Change to ClusterIP if only internal access is needed
  selector:
    app: my-app
  ports:
    - protocol: TCP
      port: 80       # Port exposed externally
      targetPort: 3000 # Container's port
