name: CI/CD App pipeline

on:
  push:
    branch: [main]
    paths: ['app/**']

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        
      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1
      
      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.ECR_URL}}:latest ./app
          docker push ${{ secrets.ECR_URL }}:latest
      
      - name: Deploy to EKS using Helm
        run: |
          helm upgrade --install nodejs-app ./helm/nodejs-app \
            --set image.repository=${{ secrets.ECR_URL }} \
            --set image.tag=latest